//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WatchShop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Image
    {
        public Image()
        {
        }

        public Image(string id, string url, string product)
        {
            Id = id;
            Url = url;
            Product = product;
        }

        public string Id { get; set; }
        public string Url { get; set; }
        public string Product { get; set; }
    
        public virtual Product Product1 { get; set; }
    }
}
