//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WatchShop.Models
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    [Table("Products")]
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.Images = new HashSet<Image>();
            this.OrderDetails = new HashSet<OrderDetail>();
        }
    

        public string Id { get; set; }
        public string Name { get; set; }
        public string Avatar { get; set; }
        [Range(0, double.MaxValue, ErrorMessage = "Price number is not valid")]
        public double Price { get; set; }

        [Range(0, 100, ErrorMessage = "Discount number is not valid")]
        public Nullable<double> Discount { get; set; }

        [Range(0, int.MaxValue, ErrorMessage = "Import number is not valid")]
        public Nullable<double> Import { get; set; }

        [Range(0, int.MaxValue, ErrorMessage = "Stock number is not valid")]
        public Nullable<double> Stock { get; set; }
        public string Brand { get; set; }
        public string Gender { get; set; }
        public string Origin { get; set; }
        [DisplayName("Warranty Period")]
        public Nullable<double> WarrantyPeriod { get; set; }
        [Range(0, double.MaxValue, ErrorMessage = "Diameter number is not valid")]
        public string Diameter { get; set; }
        public string Material { get; set; }
        public string Strap { get; set; }
        [Range(0, double.MaxValue, ErrorMessage = "Wire width number is not valid")]
        [DisplayName("Wire Width")]
        public string WireWidth { get; set; }
        public string Apparatus { get; set; }
        public string Waterproof { get; set; }
        public string Description { get; set; }
        [DisplayName("Create Date")]
        public Nullable<System.DateTime> CreateDate { get; set; }
        [DisplayName("Update Date")]
        public Nullable<System.DateTime> UpdateDate { get; set; }
        [JsonIgnore]
        public virtual Brand Brand1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        [JsonIgnore]
        public virtual ICollection<Image> Images { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        [JsonIgnore]
        public virtual ICollection<OrderDetail> OrderDetails { get; set; }
    }
}
